name: 'Setup Lazarus'
description: 'Setup Lazarus using installers from sourceforge'
inputs:
  use-cache:
    required: false
    default: 'true'
  laz-url: 
    required: false
  fpc-url: 
    required: false
  fpclazup-url:
    required: false
  fpclazup-fpccommit:
    required: false  
  fpclazup-lazcommit:
    required: false    
runs:
  using: 'node20'
  main: 'dist/index/index.js'
  post: 'dist/post/index.js'
  post-if: env.SAVE_CACHE_KEY != ''