name: 'Setup Lazarus'
description: 'Setup Lazarus using installers from sourceforge'
inputs:
  use-cache:
    required: false
    default: 'true'
  laz-url: 
    required: true
  fpc-url: 
    required: false
runs:
  using: 'node20'
  main: 'dist/index/index.js'
  post: 'dist/post/index.js'
  post-if: success() && env.SAVE_CACHE_KEY != ''  
  

